// Auto-generated by scripts/generate-redirect-map.ts
// DO NOT EDIT MANUALLY - run: npm run generate:redirects

export const LEGACY_REDIRECTS = new Map<string, string>([
  ['/catalog/smart-watches/chasy-samsung-galaxy-watch 8-classic', '/catalog/smart-watches/chasy-samsung-galaxy-watch-8-classic'],
  ['/catalog/other/Экшн-камера GoPro', '/catalog/other/ekshn-kamera-gopro'],
  ['/catalog/other/Зарядные устройства', '/catalog/other/zaryadnye-ustroystva'],
  ['/catalog/smart-watches/Часы Samsung', '/catalog/smart-watches/chasy-samsung-galaxy-watch-8'],
  ['/catalog/audio/Наушники Marshall', '/catalog/audio/naushniki-marshall'],
  ['/catalog/other/Аксессуары Apple', '/catalog/other/aksessuary-apple'],
  ['/catalog/audio/Apple AirPods Max 2 (2026)', '/catalog/audio/apple-airpods-max-2-2026'],
  ['/catalog/laptops/Apple MacBook Pro (M5, 2025)', '/catalog/laptops/apple-macbook-pro-m5-2025'],
  ['/catalog/home-appliances/Фены Dyson', '/catalog/home-appliances/feny-dyson'],
  ['/catalog/laptops/Apple MacBook Air (M5, 2026)', '/catalog/laptops/apple-macbook-air-m5-2026'],
  ['/catalog/tablets/Apple iPad Pro (M5, 2025)', '/catalog/tablets/apple-ipad-pro-m5-2025'],
  ['/catalog/tablets/Apple-iPad-Air-(M4, 2026)', '/catalog/tablets/apple-ipad-air-m4-2026'],
  ['/catalog/gaming-consoles/Геймпады-PS5', '/catalog/gaming-consoles/geympady-ps5'],
  ['/catalog/home-appliances/Выпрямитель-Dyson-HT01 ', '/catalog/home-appliances/vypryamitel-dyson-ht01'],
  ['/catalog/laptops/Apple MacBook Neo (A18 Pro, 2026)', '/catalog/laptops/apple-macbook-neo-a18-pro-2026'],
  ['/catalog/gaming-consoles/umnye-ochki', '/catalog/smart-devices/umnye-ochki'],
  ['/catalog/drugoe/umnye-ochki', '/catalog/smart-devices/umnye-ochki'],
])
