// Auto-generated by scripts/generate-redirect-map.ts
// MANUALLY UPDATED for production-404-final-patch migration
// Apple products: brand-based → productGroup-based URLs
// Dyson: corrected target slugs

export const LEGACY_REDIRECTS = new Map<string, string>([
  // Apple: brand-based URLs → productGroup-based URLs with normalized slugs
  ['/catalog/airpods/Apple AirPods Max 2 (2026)', '/catalog/audio/apple-airpods-max-2-2026'],
  ['/catalog/macbook/Apple MacBook Neo (A18 Pro, 2026)', '/catalog/laptops/apple-macbook-neo-a18-pro-2026'],
  ['/catalog/ipad/Apple-iPad-Air-(M4, 2026)', '/catalog/tablets/apple-ipad-air-m4-2026'],
  ['/catalog/ipad/Apple iPad Pro (M5, 2025)', '/catalog/tablets/apple-ipad-pro-m5-2025'],
  ['/catalog/macbook/Apple MacBook Air (M5, 2026)', '/catalog/laptops/apple-macbook-air-m5-2026'],
  ['/catalog/macbook/Apple MacBook Pro (M5, 2025)', '/catalog/laptops/apple-macbook-pro-m5-2025'],

  // Samsung: brand-based URLs → productGroup-based URLs
  ['/catalog/samsung-watch/Часы Samsung', '/catalog/smart-watches/chasy-samsung-galaxy-watch-8'],
  ['/catalog/samsung-watch/chasy-samsung-galaxy-watch 8-classic', '/catalog/smart-watches/chasy-samsung-galaxy-watch-8-classic'],

  // Other: Cyrillic → normalized slugs
  ['/catalog/audio/Наушники Marshall', '/catalog/audio/naushniki-marshall'],
  ['/catalog/other/Экшн-камера GoPro', '/catalog/other/ekshn-kamera-gopro'],

  // Dyson: brand-based URLs → productGroup-based URLs with corrected slugs
  ['/catalog/dyson/Выпрямитель-Dyson-HT01 ', '/catalog/home-appliances/vypryamitel-dyson-ht01'],
  ['/catalog/dyson/Фены Dyson', '/catalog/home-appliances/fen-dyson-supersonic-nural-hd16'],

  // Previously fixed products (Ray-Ban, DualSense)
  ['/catalog/gaming-consoles/Геймпады-PS5', '/catalog/gaming-consoles/geympady-ps5'],
  ['/catalog/playstation/Геймпады-PS5', '/catalog/gaming-consoles/geympady-ps5'],
  ['/catalog/gaming-consoles/umnye-ochki', '/catalog/smart-devices/umnye-ochki'],
  ['/catalog/drugoe/umnye-ochki', '/catalog/smart-devices/umnye-ochki'],
  ['/catalog/gaming-consoles/ray-ban-display-uq0icl', '/catalog/smart-devices/ray-ban-display-uq0icl'],
  ['/catalog/gaming-consoles/ray-ban-skyler-gen-2-rw4014-cfnorf', '/catalog/smart-devices/ray-ban-skyler-gen-2-rw4014-cfnorf'],
  ['/catalog/gaming-consoles/ray-ban-starfire-kylie-edition-classic-8i4rw8', '/catalog/smart-devices/ray-ban-starfire-kylie-edition-classic-8i4rw8'],

  // Other legacy redirects
  ['/catalog/other/Зарядные устройства', '/catalog/other/zaryadnye-ustroystva'],
  ['/catalog/other/Аксессуары Apple', '/catalog/other/aksessuary-apple'],
])
