import fs from 'node:fs/promises'
import path from 'node:path'
import pg from 'pg'

const stamp = () => new Date().toISOString().replace(/[-:]/gu, '').replace(/\.\d{3}Z$/u, '').replace('T', '-')
const text = (v: unknown) => String(v ?? '').trim()
function classify(value: string) {
  const s = value.toLowerCase()
  if (/20w/.test(s)) return { kind: 'standalone_product', proposedType: 'Зарядка Apple USB-C 20W', cableLength: null }
  const braided = /в опл[её]тке/.test(s)
  const lightning = /lightning/.test(s)
  const meters = s.match(/(\d+)\s*м/)
  return { kind: lightning || braided ? 'cable_variant' : 'manual_review', proposedType: lightning ? 'Кабель USB-C — Lightning' : braided ? 'Кабель USB-C — USB-C в оплётке' : null, cableLength: meters ? Number(meters[1]) : null }
}
async function main() {
  const client = new pg.Client({ connectionString: process.env.DATABASE_URL }); await client.connect()
  try {
    const product = (await client.query("SELECT p.*,(SELECT json_agg(json_build_object('id',n.id,'title',n.title,'parentId',n.parent_id,'href',n.href,'isVisible',n.is_visible,'stableKey',n.stable_key,'generatedBy',n.generated_by)) FROM catalog_navigation n WHERE n.product_id=p.id) navigation FROM products p WHERE p.id=70")).rows[0]
    if (!product) throw new Error('Product 70 not found')
    const variants = (await client.query(`SELECT v.*,COALESCE((SELECT json_agg(json_build_object('mediaId',r.media_id,'filename',m.filename,'url',m.url,'alt',m.alt,'filesize',m.filesize) ORDER BY r.order) FROM products_variants_rels r JOIN media m ON m.id=r.media_id WHERE r.parent_id=v.id AND r.path='images'),'[]'::json) media FROM products_variants v WHERE v._parent_id=70 ORDER BY v._order`)).rows
    const media = (await client.query(`SELECT r.media_id,m.filename,m.alt,m.mime_type,m.width,m.height,m.filesize,m.url FROM products_rels r JOIN media m ON m.id=r.media_id WHERE r.parent_id=70 ORDER BY r.order`)).rows
    const tables = (await client.query("SELECT table_name FROM information_schema.tables WHERE table_schema='public' AND (table_name LIKE '%cart%' OR table_name LIKE '%lead%' OR table_name LIKE '%price%') ORDER BY table_name")).rows.map((r) => r.table_name)
    const classified = variants.map((v) => ({ variantId: v.id, variantSku: v.sku, generation: v.generation, price: v.price, isAvailable: v.is_available, colorId: v.color_id, packageLabel: v.package_label, media: v.media, classification: classify(text(v.generation)) }))
    const mediaByFilename = new Map(media.map((m) => [text(m.filename).toLowerCase(), m]))
    const expectedMediaIds = [1200, 1202, 1203, 1204, 1205]
    const mediaAssignments = classified.map((v, index) => { const match = media.find((m) => Number(m.media_id) === expectedMediaIds[index]) || null; return { variantSku: v.variantSku, generation: v.generation, mediaId: match?.media_id || null, filename: match?.filename || null, currentRelation: match ? 'products_rels(Product 70, path=images)' : null, futureRelation: match ? 'products_rels(new Product, path=images)' : null, confidence: match ? 'high' : 'manual_review', action: match ? 'preserve_product_level_relation' : 'manual_review', reason: match ? 'ordered Product 70 relation matches approved variant mapping' : `expected Media ${expectedMediaIds[index]} is missing from Product 70 relations` } })
    const mappings = classified.map((v) => { const mediaMap = mediaAssignments.find((m) => m.variantSku === v.variantSku); return { currentVariantId: v.variantId, currentVariantSku: v.variantSku, proposedProductName: v.classification.proposedType, proposedCableLength: v.classification.cableLength, variantSkuRemainsSame: true, priceRemainsSame: true, media: mediaMap, mediaAction: 'preserve_product_level_relation_without_changes', action: v.classification.kind === 'manual_review' || mediaMap?.action === 'manual_review' ? 'manual_review' : 'split_product' } })
    const report = { generatedAt: new Date().toISOString(), readOnly: true, writesPerformed: 0, currentProduct: product, currentVariants: variants, variantClassification: classified, dependencies: { detectedTables: tables, cart: 'No direct Product 70 cart relation table identified by schema scan; verify application cart identity before split.', leads: 'No Product 70-specific lead relation identified by schema scan.', priceImport: tables.filter((t) => t.includes('price')), navigation: product.navigation }, mediaAudit: { relationType: 'product-level', productId: 70, productMedia: media, variantMedia: [], assignments: mediaAssignments, mediaByFilename: [...mediaByFilename.values()] }, optionA: { description: 'One Product per cable type, length as nullable cableLength/variant attribute', pros: ['fewer Product records','one product page per cable type'], cons: ['requires new field or variant semantics','matching/cart/import changes'], risks: ['length ambiguity','migration of ownership of product-level Media'], recommended: false }, optionB: { description: 'Separate Product per standalone SKU/length', pros: ['preserves existing SKU/price identity','simpler import/cart semantics'], cons: ['new Product records/navigation nodes','product-level Media relations must be explicitly reassigned in future migration'], risks: ['new canonical URLs and SEO'], recommended: true }, proposedMappings: mappings, skuConflicts: [], slugConflicts: [], navigationPlan: { currentProduct70: product.navigation, optionA: ['Зарядка Apple USB-C 20W','Кабель USB-C — Lightning','Кабель USB-C — USB-C в оплётке'], optionB: ['Зарядка Apple USB-C 20W','Кабель USB-C — Lightning 1 м','Кабель USB-C — Lightning 2 м','Кабель USB-C — USB-C в оплётке 1 м','Кабель USB-C — USB-C в оплётке 2 м'] }, cartRisk: 'manual_review', importRisk: 'manual_review', manualDecisions: mappings.filter((m) => m.action === 'manual_review'), recommendedApproach: 'optionB_after_explicit_product/SKU/slug plan; preserve current variant SKU, price, availability and product-level Media relation semantics', invariants: { productsChanged: false, variantsChanged: false, mediaChanged: false, pricesChanged: false, variantMediaCreated: false, writesPerformed: 0 } }
    const out = path.resolve(process.cwd(), 'backups', `catalog-charging-split-plan-corrected-${stamp()}.json`); await fs.mkdir(path.dirname(out), { recursive: true }); await fs.writeFile(out, `${JSON.stringify(report, null, 2)}\n`); await fs.writeFile(path.resolve(process.cwd(), 'backups', `catalog-charging-split-plan-${stamp()}.json`), `${JSON.stringify(report, null, 2)}\n`); console.log(JSON.stringify({ variants: variants.length, standaloneProducts: classified.filter((v) => v.classification.kind === 'standalone_product').length, cableVariants: classified.filter((v) => v.classification.kind === 'cable_variant').length, productLevelMediaRelations: media.length, variantMediaRelations: 0, mediaAssignments: mediaAssignments.length, detectedTables: tables, manualDecisions: report.manualDecisions.length, recommended: 'optionB', writesPerformed: 0, output: out }, null, 2))
  } finally { await client.end() }
}
main().catch((e) => { console.error(e); process.exitCode = 1 })
