import fs from 'node:fs/promises'
import path from 'node:path'
import pg from 'pg'

const GROUPS = [['smartphones', 'Смартфоны'], ['tablets', 'Планшеты'], ['laptops', 'Ноутбуки'], ['smart-watches', 'Смарт-часы'], ['audio', 'Наушники и аудио'], ['gaming-consoles', 'Игровые консоли'], ['home-appliances', 'Бытовая техника'], ['smart-devices', 'Умные устройства'], ['other', 'Другое']] as const
const clean = (v: unknown) => String(v ?? '').trim()
const stamp = () => new Date().toISOString().replace(/[-:]/gu, '').replace(/\.\d{3}Z$/u, '').replace('T', '-')
const rank = new Map([['Apple', 0], ['Samsung', 1], ['Sony', 2], ['Dyson', 3], ['Ray-Ban', 4]])
const norm = (v: unknown) => clean(v).toLowerCase().replace(/[\[\](),]/gu, ' ').replace(/\b(?:19|20)\d{2}\b/gu, ' ').replace(/[-_]+/gu, ' ').replace(/\s+/gu, ' ').trim().replace(/^(apple|samsung|sony|dyson|ray\s*ban)\s+/u, '')

function decisions(group: string, brand: string, rows: any[]) {
  const map = new Map<string, any[]>(); for (const row of rows) { const line = clean(row.product_line); if (line) { if (!map.has(line)) map.set(line, []); map.get(line)!.push(row) } }
  return [...map].map(([line, members]) => {
    const same = members.some((p) => norm(line) === norm(p.name) || norm(line) === norm(p.product_line)); let title: string | null = null; let decision = 'collapse_singleton'; let reason = 'line has one product'
    if (group === 'smartphones' && brand === 'Samsung') { if (/\bgalaxy\s+s\d/iu.test(line)) { title = 'Galaxy S'; decision = 'approved_business_line'; reason = 'approved Samsung family' } else if (/\bgalaxy\s+a\d/iu.test(line)) { title = 'Galaxy A'; decision = 'approved_business_line'; reason = 'approved Samsung family' } else if (/\bgalaxy\s+z/iu.test(line)) { title = 'Galaxy Z'; decision = 'approved_business_line'; reason = 'approved Samsung family' } }
    else if (group === 'gaming-consoles' && brand === 'Sony' && /^playstation\s+5/iu.test(line)) { title = 'PlayStation'; decision = 'approved_business_line'; reason = 'approved PlayStation family' }
    else if (group === 'gaming-consoles' && brand === 'Sony' && /геймпад/iu.test(line)) { title = line; decision = 'approved_business_line'; reason = 'gamepad classification' }
    else if (members.length >= 2 && !same) { title = line; decision = 'keep_line'; reason = 'multiple products grouped' }
    else if (same) { decision = 'collapse_duplicate_title'; reason = 'line matches product title' }
    return { group, brand, line, count: members.length, products: members.map((p) => ({ id: p.id, name: p.name })), decision, reason, title }
  })
}

async function main() {
  const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL }); const client = await pool.connect()
  try {
    const result = await client.query('SELECT p.*, c.slug AS category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.is_available=true ORDER BY p.sort_order NULLS LAST,p.name'); const products = result.rows as any[]; if (products.length !== 47) throw new Error(`Expected 47 available products, got ${products.length}`)
    const usable = products.filter((p) => clean(p.status).toLowerCase() !== 'used' && clean(p.category_slug).toLowerCase() !== 'used'); const grouped = new Map<string, any[]>(); for (const p of usable) { const g = GROUPS.some(([s]) => s === p.product_group) ? p.product_group : 'other'; if (!grouped.has(g)) grouped.set(g, []); grouped.get(g)!.push(p) }
    const lineDecisions = [...grouped].flatMap(([g, rows]) => [...new Set(rows.map((p) => clean(p.brand)).filter(Boolean))].flatMap((b) => decisions(g, b, rows.filter((p) => clean(p.brand) === b))))
    const report: any = { generatedAt: new Date().toISOString(), summary: { products: usable.length, groups: GROUPS.length, linesBefore: lineDecisions.length, linesAfter: new Set(lineDecisions.filter((d) => d.title).map((d) => `${d.group}:${d.brand}:${d.title}`)).size, collapsed: lineDecisions.filter((d) => !d.title).length }, lineDecisions, products: [] }
    await client.query('BEGIN'); await client.query('DELETE FROM catalog_navigation_rels WHERE catalog_navigation_id IN (SELECT id FROM catalog_navigation WHERE generated_by=$1)', ['catalog-navigation']); await client.query('DELETE FROM catalog_navigation WHERE generated_by=$1', ['catalog-navigation'])
    const ids = new Map<string, number>(); const insert = async (key: string, d: any) => { const r = await client.query('INSERT INTO catalog_navigation (title,kind,product_group,brand,product_line,href,sort_order,is_visible,is_new,badge_text,stable_key,generated_by) VALUES ($1,$2,$3,$4,$5,$6,$7,true,$8,$9,$10,$11) ON CONFLICT (stable_key) DO NOTHING RETURNING id', [d.title,d.kind,d.productGroup||null,d.brand||null,d.productLine||null,d.href||null,d.sortOrder||100,Boolean(d.isNew),d.isNew?'Новинка':null,key,'catalog-navigation']); const id = Number(r.rows[0]?.id || (await client.query('SELECT id FROM catalog_navigation WHERE stable_key=$1',[key])).rows[0].id); ids.set(key,id); return id }; const rel = async (parent: number, child: number, product?: number) => { await client.query(`INSERT INTO catalog_navigation_rels (parent_id,catalog_navigation_id,path,"order") SELECT $1,$2,'parent',$3 WHERE NOT EXISTS (SELECT 1 FROM catalog_navigation_rels WHERE parent_id=$1 AND catalog_navigation_id=$2 AND path='parent')`, [parent,child,0]); if (product) await client.query(`INSERT INTO catalog_navigation_rels (catalog_navigation_id,products_id,path,"order") SELECT $1,$2,'product',$3 WHERE NOT EXISTS (SELECT 1 FROM catalog_navigation_rels WHERE catalog_navigation_id=$1 AND products_id=$2 AND path='product')`, [child,product,0]) }
    for (const [index,[group,title]] of GROUPS.entries()) { const gid = await insert(`group:${group}`, { title, kind:'group', productGroup:group, sortOrder:index+1 }); const rows=grouped.get(group)||[]; const brands=[...new Set(rows.map((p)=>clean(p.brand)).filter(Boolean))].sort((a,b)=>(rank.get(a)??99)-(rank.get(b)??99)||a.localeCompare(b,'ru')); for (const brand of brands) { const br=rows.filter((p)=>clean(p.brand)===brand); const bid=await insert(`brand:${group}:${brand}`,{title:brand,kind:'brand',productGroup:group,brand,sortOrder:Math.min(...br.map((p)=>Number(p.sort_order)||100))}); await rel(gid,bid); const seen = new Set<string>(); for (const d of decisions(group,brand,br).filter((x)=>x.title)) { if (seen.has(d.title!)) continue; seen.add(d.title!); const members = decisions(group,brand,br).filter((x)=>x.title === d.title).flatMap((x)=>x.products); const lid=await insert(`line:${group}:${brand}:${d.title}`,{title:d.title,kind:'line',productGroup:group,brand,productLine:d.line,sortOrder:Math.min(...members.map((x:any)=>Number(br.find((p)=>p.id===x.id)?.sort_order)||100))}); await rel(bid,lid) } } }
    for (const p of usable) { const group=GROUPS.some(([s])=>s===p.product_group)?p.product_group:'other'; const brand=clean(p.brand); const d=brand?lineDecisions.find((x)=>x.group===group&&x.brand===brand&&x.products.some((q:any)=>q.id===p.id)&&x.title):null; const parent=ids.get(d?`line:${group}:${brand}:${d.title}`:brand?`brand:${group}:${brand}`:`group:${group}`)!; const pid=await insert(`product:${p.id}`,{title:p.name,kind:'product',productGroup:group,brand:brand||null,productLine:clean(p.product_line)||null,sortOrder:Number(p.sort_order)||100,href:`/catalog/${clean(p.category_slug)||'other'}/${p.slug}`,isNew:Boolean(p.is_new)}); await rel(parent,pid,Number(p.id)); report.products.push({id:p.id,parent}) }
    await client.query('UPDATE catalog_navigation n SET parent_id=r.parent_id FROM catalog_navigation_rels r WHERE r.catalog_navigation_id=n.id AND r.path=$1',['parent']); await client.query('UPDATE catalog_navigation n SET product_id=r.products_id FROM catalog_navigation_rels r WHERE r.catalog_navigation_id=n.id AND r.path=$1',['product']); await client.query('COMMIT'); const output=path.resolve(process.cwd(),'backups',`catalog-navigation-depth-apply-${stamp()}.json`); await fs.mkdir(path.dirname(output),{recursive:true}); await fs.writeFile(output,`${JSON.stringify(report,null,2)}\n`,'utf8'); console.log(JSON.stringify(report.summary,null,2)); console.log(output)
  } catch (error) { try { await client.query('ROLLBACK') } catch {} throw error } finally { client.release(); await pool.end() }
}
main().catch((error)=>{ console.error(error); process.exitCode=1 })
