import fs from 'node:fs'
import path from 'node:path'

// Read latest slug-repair-plan backup and generate static redirect map for middleware
function generateRedirectMap() {
  const backupsDir = path.join(process.cwd(), 'backups')
  const files = fs.readdirSync(backupsDir)
    .filter(f => f.startsWith('slug-repair-plan-') && f.endsWith('.json'))
    .sort()
    .reverse()

  if (files.length === 0) {
    console.log('No slug-repair-plan backups found. Generating empty redirect map.')
    writeRedirectMap([])
    return
  }

  const latestPlan = files[0]
  const planPath = path.join(backupsDir, latestPlan)
  const planData = JSON.parse(fs.readFileSync(planPath, 'utf-8'))

  console.log(`Loading redirects from: ${latestPlan}`)
  console.log(`Total fixes: ${planData.totalFixes}`)
  console.log(`Critical fixes: ${planData.criticalFixes}`)

  const redirects: Array<[string, string]> = planData.fixes
    .filter((f: any) => f.isAvailable && f.legacyUrl && f.canonicalUrl)
    .map((f: any) => [f.legacyUrl, f.canonicalUrl])

  console.log(`Generated ${redirects.length} redirects`)

  writeRedirectMap(redirects)
}

function writeRedirectMap(redirects: Array<[string, string]>) {
  const outputPath = path.join(process.cwd(), 'src', 'lib', 'legacy-redirects.ts')
  const content = `// Auto-generated by scripts/generate-redirect-map.ts
// DO NOT EDIT MANUALLY - run: npm run generate:redirects

export const LEGACY_REDIRECTS = new Map<string, string>([
${redirects.map(([from, to]) => `  ['${from}', '${to}'],`).join('\n')}
])
`

  fs.writeFileSync(outputPath, content, 'utf-8')
  console.log(`✓ Written to ${outputPath}`)
}

generateRedirectMap()
