'use client'

import React, { useEffect, useState } from 'react'
import Link from 'next/link'
import './CatalogNavigationView.scss'

type Node = { id: number; title: string; kind: string; parent?: number | { id: number } | null; isVisible?: boolean; isNew?: boolean; sortOrder?: number; coverImage?: { id?: number; filename?: string } | number | null }
const kindLabels: Record<string, string> = { group: 'Группа', brand: 'Бренд', line: 'Линейка', product: 'Товар', custom_link: 'Ссылка' }
const childLabel = (n: number) => n === 1 ? '1 дочерний пункт' : n >= 2 && n <= 4 ? `${n} дочерних пункта` : `${n} дочерних пунктов`

export default function CatalogNavigationView() {
  const [items, setItems] = useState<Node[]>([])
  const [open, setOpen] = useState<Set<number>>(new Set())
  const [menu, setMenu] = useState<number | null>(null)
  const [forbidden, setForbidden] = useState(false)
  const [canManageRoots, setCanManageRoots] = useState(false)
  const [canDeleteSubtrees, setCanDeleteSubtrees] = useState(false)
  const load = async () => { const response = await fetch('/api/catalog-navigation-admin'); if (response.status === 403) { setForbidden(true); return }; if (!response.ok) throw new Error('load failed'); const data = await response.json(); setItems(Array.isArray(data) ? data : data.docs || []); setCanManageRoots(Boolean(data.canManageRoots)); setCanDeleteSubtrees(Boolean(data.canDeleteSubtrees)) }
  useEffect(() => { load().catch(() => setItems([])) }, [])
  const children = (parent: Node | null) => items.filter((item) => (typeof item.parent === 'object' ? item.parent?.id : item.parent) === (parent?.id || null))
  const action = async (id: number, actionName: string, extra: any = {}) => { setMenu(null); const response = await fetch('/api/catalog-navigation-admin', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id, action: actionName, ...extra }) }); if (!response.ok) { const data = await response.json().catch(() => ({})); window.alert(data.error || 'Операция не выполнена'); return }; await load() }
  const addRoot = async () => { const type = window.prompt('Тип раздела: group или service_link', 'group')?.trim().toLowerCase(); if (!type) return; const kind = type === 'service_link' || type === 'custom_link' ? 'custom_link' : type; if (!['group', 'custom_link'].includes(kind)) return; const title = window.prompt('Название раздела')?.trim(); if (!title) return; const payload: any = { action: 'createRoot', kind, title }; if (kind === 'group') payload.groupKey = window.prompt('Ключ группы')?.trim(); else payload.href = window.prompt('Внутренний путь', '/trade-in')?.trim(); await action(0, 'createRoot', payload) }
  const addChild = async (parent: Node) => { setMenu(null); if (!['group', 'brand', 'line'].includes(parent.kind)) return; const kind = window.prompt('Тип дочернего пункта: brand, line или product')?.trim(); if (!kind || !['brand', 'line', 'product'].includes(kind)) return; const title = window.prompt('Название пункта')?.trim(); if (!title) return; const extra: any = { action: 'create', kind, parentId: parent.id, title }; if (kind === 'product') extra.productId = Number(window.prompt('ID существующего товара')); await action(parent.id, 'create', extra) }
  const edit = async (node: Node) => { setMenu(null); const title = window.prompt('Название пункта', node.title); if (title) await action(node.id, 'edit', { title }) }
  const deleteSubtree = async (node: Node, count: number) => { setMenu(null); if (!window.confirm('Будет удалён этот раздел и все его пункты только из навигации сайта. Товары, варианты, цены, SKU и фотографии сохранятся.')) return; const typed = window.prompt(`Введите точное название раздела: ${node.title}`); if (typed !== node.title) { window.alert('Название не совпадает. Удаление отменено.'); return }; if (!window.confirm(`Окончательно удалить раздел «${node.title}» и ${count} дочерних пунктов?`)) return; await action(node.id, 'deleteSubtree', { confirmTitle: node.title }) }
  const render = (node: Node, depth = 0): React.ReactNode => { const kids = children(node); const expanded = open.has(node.id); const active = menu === node.id; return <React.Fragment key={node.id}><div className={`catalog-tree-row depth-${depth} kind-${node.kind} ${node.isVisible === false ? 'is-hidden' : ''}`}><button type="button" className="tree-toggle" aria-label={expanded ? 'Свернуть' : 'Развернуть'} onClick={() => setOpen((current) => { const next = new Set(current); next.has(node.id) ? next.delete(node.id) : next.add(node.id); return next })}>{kids.length ? (expanded ? '−' : '+') : '·'}</button><div className="tree-title"><strong>{node.title}</strong><span className="tree-meta"><span className={`visibility-status ${node.isVisible === false ? 'hidden' : 'visible'}`}><i aria-hidden="true" />{node.isVisible === false ? 'Скрыта' : 'Видна'}</span>{node.isNew && <span className="new-status">Новинка</span>}{kids.length > 0 && <span className="children-count">{childLabel(kids.length)}</span>}<span className="kind-label">{kindLabels[node.kind] || node.kind}</span></span></div><div className="tree-menu-wrap"><button type="button" className="tree-menu-button" aria-label="Действия пункта меню" title="Действия пункта меню" aria-expanded={active} onClick={() => setMenu(active ? null : node.id)}>⋮</button>{active && <div className="tree-action-menu" role="menu"><button type="button" onClick={() => addChild(node)} disabled={!['group', 'brand', 'line'].includes(node.kind)}>Добавить дочерний пункт</button><button type="button" onClick={() => edit(node)}>Изменить</button><div className="menu-divider" /><button type="button" onClick={() => action(node.id, 'toggle')}>{node.isVisible === false ? 'Показать в меню' : 'Скрыть в меню'}</button><button type="button" onClick={() => action(node.id, 'new')}>{node.isNew ? 'Убрать новинку' : 'Пометить как новинку'}</button><div className="menu-divider" /><button type="button" onClick={() => action(node.id, 'move', { direction: -1 })}>Переместить выше</button><button type="button" onClick={() => action(node.id, 'move', { direction: 1 })}>Переместить ниже</button><div className="menu-divider" /><button type="button" className="danger" disabled={kids.length > 0} onClick={() => !kids.length && window.confirm('Пункт будет удалён только из меню. Сам товар и его данные сохранятся.') && action(node.id, 'delete')}>Удалить из меню</button>{canDeleteSubtrees && kids.length > 0 && node.kind !== 'custom_link' && <button type="button" className="danger subtree-danger" onClick={() => deleteSubtree(node, kids.length)}>Удалить раздел вместе с пунктами</button>}</div>}</div></div>{expanded && kids.sort((a, b) => (a.sortOrder || 0) - (b.sortOrder || 0)).map((child) => render(child, depth + 1))}</React.Fragment> }
  if (forbidden) return <main className="catalog-navigation-admin"><h1>Навигация каталога</h1><p>Доступ разрешён только администраторам.</p></main>
  return <main className="catalog-navigation-admin"><nav className="payload-breadcrumbs"><Link href="/admin">Панель</Link><span aria-hidden="true"> / </span><span>Навигация каталога</span></nav><Link className="payload-back-button" href="/admin">← К панели</Link><h1>Навигация каталога</h1><p className="catalog-navigation-subtitle">Управляйте порядком и видимостью пунктов меню сайта.</p>{canManageRoots && <button type="button" className="catalog-add-root" onClick={addRoot}>+ Добавить раздел</button>}<div className="catalog-tree-toolbar"><button type="button" onClick={() => setOpen(new Set(items.map((item) => item.id)))}>Раскрыть всё</button><button type="button" onClick={() => setOpen(new Set())}>Свернуть всё</button></div><section className="catalog-tree">{items.filter((item) => !(typeof item.parent === 'object' ? item.parent?.id : item.parent)).map((item) => render(item))}</section></main>
}
