/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    leads: Lead;
    pages: Page;
    colors: Color;
    'storage-options': StorageOption;
    'sim-options': SimOption;
    'device-models': DeviceModel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    'storage-options': StorageOptionsSelect<false> | StorageOptionsSelect<true>;
    'sim-options': SimOptionsSelect<false> | SimOptionsSelect<true>;
    'device-models': DeviceModelsSelect<false> | DeviceModelsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-appearance': SiteAppearance;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-appearance': SiteAppearanceSelect<false> | SiteAppearanceSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Суперадмин — полный доступ. Админ — управление каталогом и создание менеджеров. Менеджер — только редактирование товаров.
   */
  role: 'superadmin' | 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  /**
   * Рекомендуемый размер: 900×700 px. Формат: JPG, PNG или WebP. Отображается на карточке категории.
   */
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  category: number | Category;
  name: string;
  /**
   * Формируется автоматически из названия.
   */
  slug: string;
  model?: string | null;
  memory?: string | null;
  color?: string | null;
  simType?: string | null;
  /**
   * Цена по карте рассчитывается автоматически (+16%)
   */
  price: number;
  oldPrice?: number | null;
  status?: ('in_stock' | 'preorder' | 'out_of_stock') | null;
  isAvailable?: boolean | null;
  isFeatured?: boolean | null;
  isNew?: boolean | null;
  sortOrder?: number | null;
  shortDescription?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Рекомендуемый размер: 1000×1000 px (квадрат). Формат: JPG, PNG или WebP. Первое фото — основное.
   */
  images?: (number | Media)[] | null;
  /**
   * Для Apple Watch: 40mm, 42mm и т.д.
   */
  size?: string | null;
  /**
   * Выберите модель для автозаполнения и генерации вариантов.
   */
  deviceModel?: (number | null) | DeviceModel;
  /**
   * Конфигурации товара (цвет, память, размер и т.д.). Если не заданы — используются основные поля.
   */
  variants?:
    | {
        /**
         * Выберите из справочника цветов
         */
        color?: (number | null) | Color;
        /**
         * Выберите из справочника (128GB, 256GB, 42mm…)
         */
        storage?: (number | null) | StorageOption;
        /**
         * Выберите из справочника SIM-вариантов
         */
        sim?: (number | null) | SimOption;
        chip?: string | null;
        ram?: string | null;
        screenSize?: string | null;
        connectivity?: string | null;
        price: number;
        oldPrice?: number | null;
        status?: ('in_stock' | 'preorder' | 'out_of_stock') | null;
        isAvailable?: boolean | null;
        /**
         * 1000×1000 px, JPG/PNG/WebP. Пусто → общие фото товара.
         */
        images?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-models".
 */
export interface DeviceModel {
  id: number;
  /**
   * iPhone 16 Pro, MacBook Air 13″ M4, Apple Watch Series 11 и т.д.
   */
  name: string;
  category: number | Category;
  /**
   * Официальные цвета этой модели
   */
  availableColors?: (number | Color)[] | null;
  /**
   * 128GB, 256GB… или 42mm, 46mm для Watch
   */
  availableStorage?: (number | StorageOption)[] | null;
  /**
   * Оставьте пустым, если SIM не применим
   */
  availableSim?: (number | SimOption)[] | null;
  /**
   * A16, M4, M4 Pro…
   */
  chip?: string | null;
  ram?: string | null;
  screenSize?: string | null;
  /**
   * Wi-Fi, Cellular…
   */
  connectivity?: string | null;
  /**
   * Цена младшей конфигурации
   */
  basePrice?: number | null;
  /**
   * Разница между конфигурациями памяти
   */
  priceStep?: number | null;
  /**
   * Если включено, поле memory записывается как size (для Apple Watch)
   */
  storageIsSize?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  /**
   * black, ultramarine, space-gray и т.д.
   */
  value: string;
  englishLabel: string;
  russianLabel: string;
  /**
   * #RRGGBB
   */
  primaryHex: string;
  /**
   * Для двухцветных (опционально)
   */
  secondaryHex?: string | null;
  /**
   * Для каких категорий применим этот цвет
   */
  deviceTypes?: ('iphone' | 'ipad' | 'macbook' | 'apple-watch' | 'airpods' | 'playstation' | 'accessories')[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-options".
 */
export interface StorageOption {
  id: number;
  /**
   * 128GB, 256GB, 512GB, 1TB, 2TB, 40mm, 42mm и т.д.
   */
  value: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sim-options".
 */
export interface SimOption {
  id: number;
  /**
   * SIM_ESIM, ESIM
   */
  value: string;
  /**
   * SIM + eSIM, eSIM
   */
  label: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  telegram?: string | null;
  product?: (number | null) | Product;
  comment?: string | null;
  consent?: boolean | null;
  consentAt?: string | null;
  source?: ('call' | 'telegram' | 'product_form' | 'contact_form' | 'repair_form') | null;
  status?: ('new' | 'in_progress' | 'done' | 'failed' | 'cancelled') | null;
  /**
   * Внутренние заметки по заявке. Клиент их не видит.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'storage-options';
        value: number | StorageOption;
      } | null)
    | ({
        relationTo: 'sim-options';
        value: number | SimOption;
      } | null)
    | ({
        relationTo: 'device-models';
        value: number | DeviceModel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  model?: T;
  memory?: T;
  color?: T;
  simType?: T;
  price?: T;
  oldPrice?: T;
  status?: T;
  isAvailable?: T;
  isFeatured?: T;
  isNew?: T;
  sortOrder?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  size?: T;
  deviceModel?: T;
  variants?:
    | T
    | {
        color?: T;
        storage?: T;
        sim?: T;
        chip?: T;
        ram?: T;
        screenSize?: T;
        connectivity?: T;
        price?: T;
        oldPrice?: T;
        status?: T;
        isAvailable?: T;
        images?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  telegram?: T;
  product?: T;
  comment?: T;
  consent?: T;
  consentAt?: T;
  source?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  value?: T;
  englishLabel?: T;
  russianLabel?: T;
  primaryHex?: T;
  secondaryHex?: T;
  deviceTypes?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-options_select".
 */
export interface StorageOptionsSelect<T extends boolean = true> {
  value?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sim-options_select".
 */
export interface SimOptionsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-models_select".
 */
export interface DeviceModelsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  availableColors?: T;
  availableStorage?: T;
  availableSim?: T;
  chip?: T;
  ram?: T;
  screenSize?: T;
  connectivity?: T;
  basePrice?: T;
  priceStep?: T;
  storageIsSize?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  shopName?: string | null;
  phone?: string | null;
  telegramUsername?: string | null;
  telegramChannelUrl?: string | null;
  whatsappUrl?: string | null;
  address?: string | null;
  workTime?: string | null;
  mapUrl?: string | null;
  mainDomain?: string | null;
  secondaryDomain?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  aboutText?: string | null;
  homepageMediaTitle?: string | null;
  homepageMediaText?: string | null;
  /**
   * Рекомендуемый размер: 1400×1050 px (фото), 1920×1080 (видео). Формат: JPG, PNG, WebP, GIF или MP4. Первый элемент — крупно, остальные в сетку.
   */
  homepageMedia?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-appearance".
 */
export interface SiteAppearance {
  id: number;
  /**
   * Рекомендуемый размер: 1920×1080 px (Full HD). Формат: MP4 (видео) или JPG/PNG/WebP (фото). Отображается на фоне главного экрана.
   */
  heroVideo?: (number | null) | Media;
  mediaBlockTitle?: string | null;
  mediaBlockText?: string | null;
  /**
   * Рекомендуемый размер: 1400×1050 px (фото), 1920×1080 (видео). Формат: JPG, PNG, WebP, GIF или MP4. Первый элемент показывается крупно, остальные — в сетку.
   */
  mediaBlockItems?: (number | Media)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  shopName?: T;
  phone?: T;
  telegramUsername?: T;
  telegramChannelUrl?: T;
  whatsappUrl?: T;
  address?: T;
  workTime?: T;
  mapUrl?: T;
  mainDomain?: T;
  secondaryDomain?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  aboutText?: T;
  homepageMediaTitle?: T;
  homepageMediaText?: T;
  homepageMedia?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-appearance_select".
 */
export interface SiteAppearanceSelect<T extends boolean = true> {
  heroVideo?: T;
  mediaBlockTitle?: T;
  mediaBlockText?: T;
  mediaBlockItems?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}