/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'price-update-batches': PriceUpdateBatch;
    'price-update-items': PriceUpdateItem;
    'price-import-sessions': PriceImportSession;
    'price-import-items': PriceImportItem;
    leads: Lead;
    pages: Page;
    colors: Color;
    'storage-options': StorageOption;
    'sim-options': SimOption;
    'device-models': DeviceModel;
    'ram-options': RamOption;
    'variant-size-options': VariantSizeOption;
    'screen-size-options': ScreenSizeOption;
    'connectivity-options': ConnectivityOption;
    'catalog-navigation': CatalogNavigation;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'price-update-batches': PriceUpdateBatchesSelect<false> | PriceUpdateBatchesSelect<true>;
    'price-update-items': PriceUpdateItemsSelect<false> | PriceUpdateItemsSelect<true>;
    'price-import-sessions': PriceImportSessionsSelect<false> | PriceImportSessionsSelect<true>;
    'price-import-items': PriceImportItemsSelect<false> | PriceImportItemsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    colors: ColorsSelect<false> | ColorsSelect<true>;
    'storage-options': StorageOptionsSelect<false> | StorageOptionsSelect<true>;
    'sim-options': SimOptionsSelect<false> | SimOptionsSelect<true>;
    'device-models': DeviceModelsSelect<false> | DeviceModelsSelect<true>;
    'ram-options': RamOptionsSelect<false> | RamOptionsSelect<true>;
    'variant-size-options': VariantSizeOptionsSelect<false> | VariantSizeOptionsSelect<true>;
    'screen-size-options': ScreenSizeOptionsSelect<false> | ScreenSizeOptionsSelect<true>;
    'connectivity-options': ConnectivityOptionsSelect<false> | ConnectivityOptionsSelect<true>;
    'catalog-navigation': CatalogNavigationSelect<false> | CatalogNavigationSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'site-appearance': SiteAppearance;
    'brand-catalog-navigation': BrandCatalogNavigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'site-appearance': SiteAppearanceSelect<false> | SiteAppearanceSelect<true>;
    'brand-catalog-navigation': BrandCatalogNavigationSelect<false> | BrandCatalogNavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Суперадмин — полный доступ. Админ — управление каталогом и создание менеджеров. Менеджер — только редактирование товаров.
   */
  role: 'superadmin' | 'admin' | 'manager';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    detail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Сервисные категории. Товарный каталог строится через верхнюю группу, бренд, линейку и товар.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  slug: string;
  sortOrder?: number | null;
  isActive?: boolean | null;
  /**
   * Рекомендуемый размер: 900×700 px. Формат: JPG, PNG или WebP. Отображается на карточке категории.
   */
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  category?: (number | null) | Category;
  name: string;
  /**
   * Формируется автоматически из названия.
   */
  slug: string;
  model?: string | null;
  productGroup?:
    | (
        | 'smartphones'
        | 'tablets'
        | 'laptops'
        | 'smart-watches'
        | 'audio'
        | 'gaming-consoles'
        | 'home-appliances'
        | 'smart-devices'
        | 'accessories'
        | 'other'
        | 'trade-in'
      )
    | null;
  /**
   * Необязательное техническое поле; существующие товары не изменяются автоматически.
   */
  condition?: ('new' | 'used') | null;
  brand?: string | null;
  /**
   * Выберите тип устройства до настройки вариантов.
   */
  deviceType?: string | null;
  /**
   * Выберите тип до добавления вариантов.
   */
  productType?: string | null;
  productLine?: string | null;
  /**
   * Используется для массового обновления цен
   */
  sku?: string | null;
  badge?: string | null;
  memory?: string | null;
  color?: string | null;
  simType?: string | null;
  /**
   * Базовая розничная цена рассчитывается автоматически (+20%)
   */
  price: number;
  status?: ('in_stock' | 'preorder' | 'out_of_stock') | null;
  isAvailable?: boolean | null;
  /**
   * Если включено — цвета, для которых все варианты недоступны, не будут показываться на странице товара.
   */
  hideUnavailableColors?: boolean | null;
  isFeatured?: boolean | null;
  isNew?: boolean | null;
  /**
   * Используется для технического порядка карточек в каталоге.
   */
  sortOrder?: number | null;
  shortDescription?: string | null;
  /**
   * Устаревшее поле сохранено для обратной совместимости.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Рекомендуемый размер: 1000×1000 px (квадрат). Формат: JPG, PNG или WebP. Первое фото — основное.
   */
  images?: (number | Media)[] | null;
  /**
   * Загрузите фото для каждого цвета. При выборе цвета на сайте показываются соответствующие фото. Если не заданы — общие фото товара.
   */
  colorImages?:
    | {
        color: number | Color;
        images: (number | Media)[];
        id?: string | null;
      }[]
    | null;
  /**
   * Для Apple Watch: 40mm, 42mm и т.д.
   */
  size?: string | null;
  /**
   * Выберите модель для автозаполнения и генерации вариантов.
   */
  deviceModel?: (number | null) | DeviceModel;
  /**
   * Конфигурации товара (цвет, память, размер и т.д.). Если не заданы — используются основные поля.
   */
  variants?:
    | {
        /**
         * Формируется автоматически при создании варианта.
         */
        sku?: string | null;
        /**
         * Выберите из справочника цветов
         */
        color?: (number | null) | Color;
        /**
         * Выберите накопитель из справочника (128GB, 256GB, 512GB, 1TB, 2TB)
         */
        storage?: (number | null) | StorageOption;
        /**
         * Выберите eSIM или SIM + eSIM из справочника
         */
        sim?: (number | null) | SimOption;
        chip?: string | null;
        ram?: string | null;
        /**
         * Выберите RAM для Mac; старое текстовое поле сохраняется.
         */
        ramOption?: (number | null) | RamOption;
        /**
         * Старое значение сохранено для совместимости; новое значение можно выбрать рядом.
         */
        size?: string | null;
        /**
         * Размер корпуса Apple Watch из справочника.
         */
        sizeOption?: (number | null) | VariantSizeOption;
        /**
         * Показывается для конфигураций Mac и сохранённых значений.
         */
        hasTouchId?: boolean | null;
        screenSize?: string | null;
        screenSizeOption?: (number | null) | ScreenSizeOption;
        connectivity?: string | null;
        /**
         * Для iPad выберите Wi-Fi/LTE, для AirPods — USB-C/Lightning, если значение есть в справочнике.
         */
        connectivityOption?: (number | null) | ConnectivityOption;
        generation?: string | null;
        revision?: string | null;
        /**
         * Существующая комплектация или описание ремешка. Не используйте generation для комплектации.
         */
        packageLabel?: string | null;
        price: number;
        status?: ('in_stock' | 'preorder' | 'out_of_stock') | null;
        isAvailable?: boolean | null;
        /**
         * 1000×1000 px, JPG/PNG/WebP. Пусто → общие фото товара.
         */
        images?: (number | Media)[] | null;
        material?: string | null;
        strapSize?: string | null;
        id?: string | null;
      }[]
    | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors".
 */
export interface Color {
  id: number;
  /**
   * black, ultramarine, space-gray и т.д.
   */
  value: string;
  englishLabel: string;
  russianLabel: string;
  /**
   * #RRGGBB
   */
  primaryHex: string;
  /**
   * Для двухцветных (опционально)
   */
  secondaryHex?: string | null;
  /**
   * Для каких категорий применим этот цвет
   */
  deviceTypes?: ('iphone' | 'ipad' | 'macbook' | 'apple-watch' | 'airpods' | 'playstation' | 'accessories')[] | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-models".
 */
export interface DeviceModel {
  id: number;
  /**
   * iPhone 16 Pro, MacBook Air 13″ M4, Apple Watch Series 11 и т.д.
   */
  name: string;
  category: number | Category;
  /**
   * Официальные цвета этой модели
   */
  availableColors?: (number | Color)[] | null;
  /**
   * 128GB, 256GB… или 42mm, 46mm для Watch
   */
  availableStorage?: (number | StorageOption)[] | null;
  /**
   * Размеры корпуса часов из отдельного справочника.
   */
  availableSizes?: (number | VariantSizeOption)[] | null;
  /**
   * Оставьте пустым, если SIM не применим
   */
  availableSim?: (number | SimOption)[] | null;
  /**
   * A16, M4, M4 Pro…
   */
  chip?: string | null;
  ram?: string | null;
  screenSize?: string | null;
  /**
   * Wi-Fi, Cellular…
   */
  connectivity?: string | null;
  /**
   * Цена младшей конфигурации
   */
  basePrice?: number | null;
  /**
   * Разница между конфигурациями памяти
   */
  priceStep?: number | null;
  /**
   * Если включено, поле memory записывается как size (для Apple Watch)
   */
  storageIsSize?: boolean | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-options".
 */
export interface StorageOption {
  id: number;
  /**
   * 128GB, 256GB, 512GB, 1TB, 2TB
   */
  value: string;
  sortOrder?: number | null;
  /**
   * Архивные записи не предлагаются для новых вариантов.
   */
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-size-options".
 */
export interface VariantSizeOption {
  id: number;
  key: string;
  label: string;
  sortOrder?: number | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sim-options".
 */
export interface SimOption {
  id: number;
  /**
   * SIM_ESIM, ESIM
   */
  value: string;
  /**
   * SIM + eSIM, eSIM
   */
  label: string;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ram-options".
 */
export interface RamOption {
  id: number;
  key: string;
  label: string;
  sortOrder?: number | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screen-size-options".
 */
export interface ScreenSizeOption {
  id: number;
  key: string;
  label: string;
  sortOrder?: number | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connectivity-options".
 */
export interface ConnectivityOption {
  id: number;
  key: string;
  label: string;
  sortOrder?: number | null;
  archived?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Журнал предпросмотров и подтверждений массового обновления цен.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-update-batches".
 */
export interface PriceUpdateBatch {
  id: number;
  author: number | User;
  sourceText: string;
  status: 'preview' | 'confirming' | 'confirmed' | 'failed' | 'expired';
  confirmationToken: string;
  expiresAt: string;
  confirmedAt?: string | null;
  totalLines: number;
  readyCount: number;
  errorCount: number;
  updatedCount: number;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-update-items".
 */
export interface PriceUpdateItem {
  id: number;
  author: number | User;
  batch: number | PriceUpdateBatch;
  lineNumber: number;
  sourceLine: string;
  sku?: string | null;
  matchType?: ('product' | 'variant') | null;
  product?: (number | null) | Product;
  productLabel?: string | null;
  variantId?: string | null;
  oldCashPrice?: number | null;
  newCashPrice?: number | null;
  oldCardPrice?: number | null;
  newCardPrice?: number | null;
  status: 'ready' | 'not_found' | 'invalid_price' | 'duplicate_sku_in_input' | 'conflict' | 'updated' | 'failed';
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-import-sessions".
 */
export interface PriceImportSession {
  id: number;
  author: number | User;
  sourceText: string;
  questions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  status: 'matching' | 'resolved' | 'previewed' | 'expired' | 'failed';
  sessionToken: string;
  expiresAt: string;
  totalItems: number;
  resolvedCount: number;
  skippedCount: number;
  previewBatch?: (number | null) | PriceUpdateBatch;
  errorMessage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-import-items".
 */
export interface PriceImportItem {
  id: number;
  author: number | User;
  session: number | PriceImportSession;
  itemNumber: number;
  sourceLine: string;
  contextHeading?: string | null;
  modelText: string;
  price: number;
  storage?: string | null;
  ram?: string | null;
  color?: string | null;
  sim?: string | null;
  region?: string | null;
  revision?: string | null;
  manufacturerModelNumber?: string | null;
  notes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  matchStatus: 'matched' | 'ambiguous' | 'not_found' | 'missing_attributes' | 'manual_review' | 'excluded_used';
  reason: string;
  candidates:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resolution: 'pending' | 'automatic' | 'manual' | 'skipped';
  selectedCandidateKey?: string | null;
  selectedSku?: string | null;
  selectedProduct?: (number | null) | Product;
  selectedVariantId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name?: string | null;
  phone?: string | null;
  email?: string | null;
  telegram?: string | null;
  product?: (number | null) | Product;
  comment?: string | null;
  consent?: boolean | null;
  consentAt?: string | null;
  source?:
    | (
        | 'call'
        | 'telegram'
        | 'product_form'
        | 'contact_form'
        | 'repair_form'
        | 'trade_in_form'
        | 'installment_form'
        | 'cart_order'
      )
    | null;
  status?: ('new' | 'in_progress' | 'done' | 'failed' | 'cancelled') | null;
  telegramStatus?: ('not_sent' | 'telegram_sent' | 'telegram_failed') | null;
  /**
   * UTM-параметры из URL (utm_source, utm_medium, utm_campaign, utm_term, utm_content)
   */
  utm?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Внутренние заметки по заявке. Клиент их не видит.
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-navigation".
 */
export interface CatalogNavigation {
  id: number;
  title: string;
  kind: 'group' | 'brand' | 'line' | 'product' | 'custom_link';
  parent?: (number | null) | CatalogNavigation;
  productGroup?: string | null;
  brand?: string | null;
  productLine?: string | null;
  product?: (number | null) | Product;
  /**
   * Обложка раздела. Связь можно очистить без удаления Media.
   */
  coverImage?: (number | null) | Media;
  href?: string | null;
  sortOrder: number;
  isVisible?: boolean | null;
  isNew?: boolean | null;
  badgeText?: string | null;
  description?: string | null;
  stableKey: string;
  generatedBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'price-update-batches';
        value: number | PriceUpdateBatch;
      } | null)
    | ({
        relationTo: 'price-update-items';
        value: number | PriceUpdateItem;
      } | null)
    | ({
        relationTo: 'price-import-sessions';
        value: number | PriceImportSession;
      } | null)
    | ({
        relationTo: 'price-import-items';
        value: number | PriceImportItem;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'colors';
        value: number | Color;
      } | null)
    | ({
        relationTo: 'storage-options';
        value: number | StorageOption;
      } | null)
    | ({
        relationTo: 'sim-options';
        value: number | SimOption;
      } | null)
    | ({
        relationTo: 'device-models';
        value: number | DeviceModel;
      } | null)
    | ({
        relationTo: 'ram-options';
        value: number | RamOption;
      } | null)
    | ({
        relationTo: 'variant-size-options';
        value: number | VariantSizeOption;
      } | null)
    | ({
        relationTo: 'screen-size-options';
        value: number | ScreenSizeOption;
      } | null)
    | ({
        relationTo: 'connectivity-options';
        value: number | ConnectivityOption;
      } | null)
    | ({
        relationTo: 'catalog-navigation';
        value: number | CatalogNavigation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        detail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sortOrder?: T;
  isActive?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  category?: T;
  name?: T;
  slug?: T;
  model?: T;
  productGroup?: T;
  condition?: T;
  brand?: T;
  deviceType?: T;
  productType?: T;
  productLine?: T;
  sku?: T;
  badge?: T;
  memory?: T;
  color?: T;
  simType?: T;
  price?: T;
  status?: T;
  isAvailable?: T;
  hideUnavailableColors?: T;
  isFeatured?: T;
  isNew?: T;
  sortOrder?: T;
  shortDescription?: T;
  description?: T;
  images?: T;
  colorImages?:
    | T
    | {
        color?: T;
        images?: T;
        id?: T;
      };
  size?: T;
  deviceModel?: T;
  variants?:
    | T
    | {
        sku?: T;
        color?: T;
        storage?: T;
        sim?: T;
        chip?: T;
        ram?: T;
        ramOption?: T;
        size?: T;
        sizeOption?: T;
        hasTouchId?: T;
        screenSize?: T;
        screenSizeOption?: T;
        connectivity?: T;
        connectivityOption?: T;
        generation?: T;
        revision?: T;
        packageLabel?: T;
        price?: T;
        status?: T;
        isAvailable?: T;
        images?: T;
        material?: T;
        strapSize?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-update-batches_select".
 */
export interface PriceUpdateBatchesSelect<T extends boolean = true> {
  author?: T;
  sourceText?: T;
  status?: T;
  confirmationToken?: T;
  expiresAt?: T;
  confirmedAt?: T;
  totalLines?: T;
  readyCount?: T;
  errorCount?: T;
  updatedCount?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-update-items_select".
 */
export interface PriceUpdateItemsSelect<T extends boolean = true> {
  author?: T;
  batch?: T;
  lineNumber?: T;
  sourceLine?: T;
  sku?: T;
  matchType?: T;
  product?: T;
  productLabel?: T;
  variantId?: T;
  oldCashPrice?: T;
  newCashPrice?: T;
  oldCardPrice?: T;
  newCardPrice?: T;
  status?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-import-sessions_select".
 */
export interface PriceImportSessionsSelect<T extends boolean = true> {
  author?: T;
  sourceText?: T;
  questions?: T;
  status?: T;
  sessionToken?: T;
  expiresAt?: T;
  totalItems?: T;
  resolvedCount?: T;
  skippedCount?: T;
  previewBatch?: T;
  errorMessage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-import-items_select".
 */
export interface PriceImportItemsSelect<T extends boolean = true> {
  author?: T;
  session?: T;
  itemNumber?: T;
  sourceLine?: T;
  contextHeading?: T;
  modelText?: T;
  price?: T;
  storage?: T;
  ram?: T;
  color?: T;
  sim?: T;
  region?: T;
  revision?: T;
  manufacturerModelNumber?: T;
  notes?: T;
  matchStatus?: T;
  reason?: T;
  candidates?: T;
  resolution?: T;
  selectedCandidateKey?: T;
  selectedSku?: T;
  selectedProduct?: T;
  selectedVariantId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  telegram?: T;
  product?: T;
  comment?: T;
  consent?: T;
  consentAt?: T;
  source?: T;
  status?: T;
  telegramStatus?: T;
  utm?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "colors_select".
 */
export interface ColorsSelect<T extends boolean = true> {
  value?: T;
  englishLabel?: T;
  russianLabel?: T;
  primaryHex?: T;
  secondaryHex?: T;
  deviceTypes?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storage-options_select".
 */
export interface StorageOptionsSelect<T extends boolean = true> {
  value?: T;
  sortOrder?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sim-options_select".
 */
export interface SimOptionsSelect<T extends boolean = true> {
  value?: T;
  label?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "device-models_select".
 */
export interface DeviceModelsSelect<T extends boolean = true> {
  name?: T;
  category?: T;
  availableColors?: T;
  availableStorage?: T;
  availableSizes?: T;
  availableSim?: T;
  chip?: T;
  ram?: T;
  screenSize?: T;
  connectivity?: T;
  basePrice?: T;
  priceStep?: T;
  storageIsSize?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ram-options_select".
 */
export interface RamOptionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  sortOrder?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variant-size-options_select".
 */
export interface VariantSizeOptionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  sortOrder?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screen-size-options_select".
 */
export interface ScreenSizeOptionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  sortOrder?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "connectivity-options_select".
 */
export interface ConnectivityOptionsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  sortOrder?: T;
  archived?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "catalog-navigation_select".
 */
export interface CatalogNavigationSelect<T extends boolean = true> {
  title?: T;
  kind?: T;
  parent?: T;
  productGroup?: T;
  brand?: T;
  productLine?: T;
  product?: T;
  coverImage?: T;
  href?: T;
  sortOrder?: T;
  isVisible?: T;
  isNew?: T;
  badgeText?: T;
  description?: T;
  stableKey?: T;
  generatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  shopName?: string | null;
  phone?: string | null;
  telegramUsername?: string | null;
  telegramChannelUrl?: string | null;
  whatsappUrl?: string | null;
  address?: string | null;
  workTime?: string | null;
  mapUrl?: string | null;
  mainDomain?: string | null;
  secondaryDomain?: string | null;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  aboutText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-appearance".
 */
export interface SiteAppearance {
  id: number;
  /**
   * Добавьте несколько фото или видео. Они будут автоматически сменяться каждые 7 секунд. Рекомендуемый размер: 1920×1080 px. Формат: MP4, JPG, PNG, WebP.
   */
  heroSlides?: (number | Media)[] | null;
  /**
   * Используется как fallback, если слайды не заданы.
   */
  heroVideo?: (number | null) | Media;
  /**
   * Товары показываются на главной в этом порядке. Можно найти товар по названию и быстро изменить порядок.
   */
  bestOffers?: (number | Product)[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-catalog-navigation".
 */
export interface BrandCatalogNavigation {
  id: number;
  groups: {
    title: string;
    key: string;
    href?: string | null;
    filter?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
    sortOrder?: number | null;
    isVisible?: boolean | null;
    isNew?: boolean | null;
    coverImage?: (number | null) | Media;
    children?:
      | {
          title: string;
          key: string;
          href?: string | null;
          filter?:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          sortOrder?: number | null;
          isVisible?: boolean | null;
          isNew?: boolean | null;
          coverImage?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  shopName?: T;
  phone?: T;
  telegramUsername?: T;
  telegramChannelUrl?: T;
  whatsappUrl?: T;
  address?: T;
  workTime?: T;
  mapUrl?: T;
  mainDomain?: T;
  secondaryDomain?: T;
  heroTitle?: T;
  heroSubtitle?: T;
  aboutText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-appearance_select".
 */
export interface SiteAppearanceSelect<T extends boolean = true> {
  heroSlides?: T;
  heroVideo?: T;
  bestOffers?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "brand-catalog-navigation_select".
 */
export interface BrandCatalogNavigationSelect<T extends boolean = true> {
  groups?:
    | T
    | {
        title?: T;
        key?: T;
        href?: T;
        filter?: T;
        sortOrder?: T;
        isVisible?: T;
        isNew?: T;
        coverImage?: T;
        children?:
          | T
          | {
              title?: T;
              key?: T;
              href?: T;
              filter?: T;
              sortOrder?: T;
              isVisible?: T;
              isNew?: T;
              coverImage?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}